# Generated by Django 5.2.4 on 2025-08-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_size_rename_avalable_product_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
    ]
