# Generated by Django 5.2.4 on 2025-08-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartproduct_quantity'),
        ('shop', '0003_size_rename_avalable_product_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.size', verbose_name='Размер'),
        ),
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('cart', 'product', 'size')},
        ),
    ]
